### ISSUE TITLE
Mark replies as reply and highlight their target on hover

### ISSUE THREAD

**Issue by Vogel612** [Vogel612/testclient_javabot#17]
Currently replies are looking a little boring. mostly because replies aren't properly marked and the message id for a reply is included in the rendered text.

It would be cool to allow marking a reply as such and highlight the message replied to on hover

**Comment by TheItachiUchiha** [comment]
Can you explain or better add an example for "allow marking a reply as such and highlight the message replied to on hover" ?

**Comment by Vogel612** [comment]
As of now we have no reply functionality whatsoever. Comparing this to the SE chat: if a message is a reply, you get that small arrow on the left-hand side of the message. Clicking that arrow redirects you to the message which was replied to.

Additionally hovering over a message highlights the message replied to as well as the messages which are replies to this message:

![screenshot of behavior observed in the Shadow's den](https://cloud.githubusercontent.com/assets/7288995/6062797/bdac7eb8-ad52-11e4-83a4-23f6e1e761fd.png)

**Comment by Vogel612** [comment]
After a little discussion with @TheItachiUchiha  in the second monitor this will not be supported. Instead the reply syntax will be stripped out.

It might be possible to later introduce a "debug-mode" which includes much more information. In that case the reply should be visible. This means removing the reply syntax should be a GUI-Hiding and not actually stripping this from the message
