### ISSUE TITLE
Add Licensing to the Repository

### ISSUE THREAD

**Issue by Vogel612** [Vogel612/testclient_javabot#5]
The repository could use a proper license. This may be dependent on what type of license is used for JavaBot, since it is used here. I already opened an issue at JavaBot: https://github.com/Vincentyification/JavaBot/issues/30

**Comment by Vogel612** [comment]
I have been informed, that JavaBot will be licensed under the Apache Software License. Until further evaluation of the exact terms of use (and I understand it well enough) development is on hiatus

**Comment by Unihedro** [comment]
I completed the other ticket, so you can do this now.
